swagger: '2.0'
info:
  title: Bank Argent API documentation for transactions 
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/{userId}:
    get:
      tags:
        - Transaction Module
      summary: Find user's transactions by user id
      description: Return transactions for one user
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of user to return transactions
          required: true
          schema:
            type:string
            # $ref: '#/definitions/Transactions'
      produces:
        - application/json
      responses:
        '200':
          description: Fetch transaction Successfully
          schema:
            $ref: '#/definitions/Transactions'
        '404':
          description: Transactions not found
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Find transaction by id
      description: Return one transaction 
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionId
          description: id for return transaction
          required: true
          schema:
            type:string
            # $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Fetch transactions list Successfully
          schema:
            properties:
              status:
                type: integer
                example: 200
              data:
                type: object
                $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactions/{userId}/addOneTransaction:
    post:
      tags:
        - Transaction Module
      summary: Add new transaction
      description: New transaction 
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of user of new transaction
          required: true
          schema:
            type:string
            # $ref: '#/definitions/Transaction'
        - in: body
          name: body
          description: body for add transaction request
          required: true
          schema:
            type: object
            properties:
              typeOfBalance:
                type: string
                example: Current
              typeOfTransaction:
                type: string
                example: Checking
              amount:
                type: number
                example: 2082.79
              currency:
                type: string
                example: USD
          
      produces:
        - application/json
      responses:
        '200':
          description: Add transaction Successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: Transaction saved!
              data:
                type: object
                $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        example: "1"
      amount:
        type: integer
        example: 2082.79
      typeOfTransaction:
        type: string
        example: Checking
      typeOfBalance:
        type: string
        example: Current
      userId: 
        type: string 
        example: "6"
  Transactions:
    type: object
    properties:
        data:
            type: array
            items:
             $ref: '#/definitions/Transaction'
