swagger: '2.0'
info:
  title: Bank Argent API documentation for transactions
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/{userId}/{accountId}:
    get:
      tags:
        - Transaction Module
      summary: Find user's transactions by user id
      description: Return transactions for one user
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of user to return transactions
          required: true
          schema:
            type:string
            # $ref: '#/definitions/Transactions'
      produces:
        - application/json
      responses:
        '200':
          description: Fetch transaction Successfully
          schema:
            properties:
              status:
                type: integer
                example: 200
              data:
                $ref: '#/definitions/Transactions'
        '404':
          description: Transactions not found
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Find transaction by id
      description: Return one transaction
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionId
          description: id for return transaction
          required: true
          schema:
            type:string
            # $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Fetch transactions list Successfully
          schema:
            properties:
              status:
                type: integer
                example: 200

              data:
                $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactionUpdate/{transactionId}:
    put:
      tags:
        - Transaction Module
      summary: Add new transaction
      description: New transaction
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          schema:
            type:string
            # $ref: '#/definitions/Transaction'
        - in: body
          name: body
          description: body for add transaction request
          required: true
          schema:
            type: object
            properties:
              category:
                type: object
                properties:
                  id:
                    type: string
                    example: 1454
                  name:
                    type: string
                    example: food
              notes:
                type: string
                example: my notes

      produces:
        - application/json
      responses:
        '200':
          description: Add transaction Successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: Transaction saved!
              data:
                type: object
                $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Transaction unauthorized
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              message:
                type: string
                example: Transaction refusé

        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        example: '112'
      date:
        type: date
        example: June 20th, 2020
      description:
        type: string
        example: Golden Sun Bakery
      amount:
        type: number
        example: 5.00
      balance:
        type: number
        example: '2089.79'
      details:
        type: array
        items:
          $ref: '#/definitions/Details'

  Details:
    type: object
    properties:
      transactionType:
        type: object
        properties:
          id:
            type: string
            example: 11545
          name:
            type: string
            example: Electronic
      category:
        type: object
        properties:
          id:
            type: string
            example: 1455
          name:
            type: string
            example: Food
      notes:
        type: object
        properties:
          content:
            type: string
            example: 'notes example'

  Transactions:
    type: array
    items:
      $ref: '#/definitions/Transaction'
